//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? 6? 20 2017 18:59:22
//
//      Input file      : 
//      Component name  : data_collect
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module data_collect(D0, CLK0, RST0, EOC0, ALE0, START0, OE0, ADDA0, WEI0, DUAN0);
   input [7:0]  D0;
   input        CLK0;
   input        RST0;
   input        EOC0;
   output       ALE0;
   output       START0;
   output       OE0;
   output       ADDA0;
   output [5:0] WEI0;
   output [7:0] DUAN0;
   
   wire [7:0]   net;
   
   ADC0809 u1(.d(D0), .clk(CLK0), .rst(RST0), .eoc(EOC0), .ale(ALE0), .start(START0), .oe(OE0), .adda(ADDA0), .q(net));
   
   shuma u2(.clk1(CLK0), .rst1(RST0), .data(net), .wei(WEI0), .duan(DUAN0));
   
endmodule
