// Copyright (C) 2016  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.1 (Build Build 196 10/24/2016)
// Created on Tue Jun 20 12:41:43 2017

data_collect data_collect_inst
(
	.D0(D0_sig) ,	// input [7:0] D0_sig
	.CLK0(CLK0_sig) ,	// input  CLK0_sig
	.RST0(RST0_sig) ,	// input  RST0_sig
	.EOC0(EOC0_sig) ,	// input  EOC0_sig
	.ALE0(ALE0_sig) ,	// output  ALE0_sig
	.START0(START0_sig) ,	// output  START0_sig
	.OE0(OE0_sig) ,	// output  OE0_sig
	.ADDA0(ADDA0_sig) ,	// output  ADDA0_sig
	.WEI0(WEI0_sig) ,	// output [5:0] WEI0_sig
	.DUAN0(DUAN0_sig) 	// output [7:0] DUAN0_sig
);

