//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// ?? 6? 20 2017 19:16:11
//
//      Input file      : 
//      Component name  : pack
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


`ifndef pack
`define pack

function [0:9][0:2] convert;
   input [7:0] D;
   reg [3:0]   dat[0:2];
   reg [3:0]   datc;
   reg [7:0]   odata;
begin
   odata = D;
   dat[0] = odataRem10;
   datc = odataRem100;
   dat[1] = datc % 10;
   dat[2] = odata % 100;
   convert = dat;
end
endfunction

`endif
